version: 0.0
os: linux
files:
  - source: .
    destination: /project/Techniques
hooks:
  BeforeInstall:
    - location: update_repo.sh
      timeout: 300
      runas: root
  ApplicationStart:
   - location: run.sh
     timeout: 300
     runas: root
