version: 0.0
os: linux
files:
  - source: .
    destination: /projects/Techniques
hooks:
  BeforeInstall:
  - location: scripts/setup.sh
    location: scripts/stop.sh
    timeout: 300
    runas: root
  ApplicationStart:
   - location: scripts/run.sh
     timeout: 300
     runas: root
