version: '3.9'

services:
  # database:
  #   image: mysql
  #   volumes:
  #     - db-data:/var/lib/mysql/data
  #   container_name: godockerDB
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=judo-test-password

  web:
    build: .
    ports:
      - 8000:8000

