version: '3.9'

services:
  web:
    build: .
    ports:
      - 8787:8787

  database:
    image: mysql
    container_name: godockerDB
    ports:
        - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=judo-test-password

