version: '2'

services:
  web:
    image: techniques
    ports:
      - 8787:8787
    depends_on:
      - database

  database:
    image: mysql/mysql-server:latest
    ports:
        - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=judo-test-password
    volumes:
      - /data:/var/lib/mysql
