version: '2.2'

services:
  web:
    build: .
    ports:
      - 8787:8787

  database:
    image: mysql
    container_name: godockerDB
    ports:
        - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=judo-test-password
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: judo-test-password
      MYSQL_DATABASE: techniques

volumes:
  db_data: {}
