version: '2.2'

services:
  database:
    image: mysql
    container_name: godockerDB
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=judo-test-password
      - MYSQL_DATABASE=techniques
    volumes:
      - mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 30s

  web:
    build: .
    ports:
      - "8787:8787"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_PASSWORD=judo-test-password
      - DB_HOST=godockerDB
      - DB_USER=root
      - DB_NAME=techniques
    restart: always # Ens
