version: '3.9'

services:
  web:
    build: .
    ports:
      - 8787:8787

  database:
    image: mysql
    ports:
        - 3636:3636
    environment:
      - MYSQL_ROOT_PASSWORD=judo-test-password
